import React, { useEffect, useState } from "react";
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  RefreshControl,
  Alert,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { ConcernService } from "../../services/concernService";
import { useAuth } from "../../context/AuthContext";
import { getStatusConfig, getCategoryConfig, RADIUS, SHADOWS } from "../../utils/theme";
import { useTheme } from "../../context/ThemeContext";
import { scale, verticalScale, rf, moderateScale } from "../../utils/responsive";

export default function AdminDashboardScreen({ navigation }) {
  const { colors } = useTheme();
  const { user } = useAuth();
  const [concerns, setConcerns] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const loadData = async () => {
    try {
      const data = await ConcernService.getConcerns();
      setConcerns(data);
    } catch {
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    loadData();
    // Auto refresh every 30 seconds
    const interval = setInterval(loadData, 30000);
    return () => clearInterval(interval);
  }, []);

  const stats = {
    total: concerns.length,
    pending: concerns.filter((c) => c.status === "Pending").length,
    inProgress: concerns.filter((c) => c.status === "In Progress").length,
    resolved: concerns.filter((c) => c.status === "Resolved").length,
    rejected: concerns.filter((c) => c.status === "Rejected").length,
  };
  const resolutionRate = stats.total
    ? Math.round((stats.resolved / stats.total) * 100)
    : 0;

  const urgent = concerns.filter(
    (c) => c.priority === "High" && c.status === "Pending",
  );
  const recent = concerns.slice(0, 6);

  const categoryCount = concerns.reduce((acc, c) => {
    acc[c.category] = (acc[c.category] || 0) + 1;
    return acc;
  }, {});
  const topCategory = Object.entries(categoryCount).sort(
    (a, b) => b[1] - a[1],
  )[0];

  const onRefresh = () => {
    setRefreshing(true);
    loadData();
  };

  const handleExportReport = () => {
    const reportDate = new Date().toLocaleDateString("en-PH", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    const reportText = `
CITIVOICE SYSTEM REPORT
Date: ${reportDate}
---------------------------
TOTAL CONCERNS: ${stats.total}
PENDING: ${stats.pending}
IN PROGRESS: ${stats.inProgress}
RESOLVED: ${stats.resolved}
REJECTED: ${stats.rejected}
---------------------------
RESOLUTION RATE: ${resolutionRate}%
URGENT CONCERNS: ${urgent.length}
TOP CATEGORY: ${topCategory ? topCategory[0] : "N/A"}
---------------------------
Report generated by ${user?.name || "Admin"}
    `;
    Alert.alert("System Report Generated", "Your report is ready.", [
      { text: "Cancel", style: "cancel" },
      { text: "View Report", onPress: () => Alert.alert("Exported Report", reportText) },
    ]);
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.bgDark }]} edges={["top"]}>
      <ScrollView
        contentContainerStyle={styles.scroll}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={onRefresh}
            tintColor={colors.accent}
          />
        }
      >
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={[styles.greeting, { color: colors.textSecondary }]}>Admin Panel 🛡️</Text>
            <Text style={[styles.adminName, { color: colors.textPrimary }]}>{user?.name}</Text>
          </View>
          <TouchableOpacity style={[styles.exportBtn, { backgroundColor: colors.accent + "22", borderColor: colors.accent + "44" }]} onPress={handleExportReport}>
            <Ionicons name="document-text" size={18} color={colors.accent} />
            <Text style={[styles.exportText, { color: colors.accent }]}>Report</Text>
          </TouchableOpacity>
        </View>

        {/* KPI Cards */}
        <View style={styles.kpiGrid}>
          {[
            {
              label: "Total",
              value: stats.total,
              icon: "📋",
              color: colors.primary,
            },
            {
              label: "Pending",
              value: stats.pending,
              icon: "⏳",
              color: colors.statusPending,
            },
            {
              label: "Active",
              value: stats.inProgress,
              icon: "🔄",
              color: colors.primaryLight,
            },
            {
              label: "Resolved",
              value: stats.resolved,
              icon: "✅",
              color: colors.accent,
            },
          ].map((k, i) => (
            <View key={i} style={[styles.kpiCard, { backgroundColor: colors.bgCard, borderColor: colors.border, borderTopColor: k.color }]}>
              <Text style={styles.kpiIcon}>{k.icon}</Text>
              <Text style={[styles.kpiNum, { color: k.color }]}>{k.value}</Text>
              <Text style={[styles.kpiLabel, { color: colors.textMuted }]}>{k.label}</Text>
            </View>
          ))}
        </View>

        {/* Resolution Rate Bar */}
        <View style={[styles.rateCard, { backgroundColor: colors.bgCard, borderColor: colors.border }]}>
          <View style={styles.rateHeader}>
            <Text style={[styles.rateTitle, { color: colors.textPrimary }]}>🎯 Resolution Rate</Text>
            <Text
              style={[
                styles.ratePercent,
                {
                  color:
                    resolutionRate > 60 ? colors.accent : colors.statusPending,
                },
              ]}
            >
              {resolutionRate}%
            </Text>
          </View>
          <View style={[styles.rateBarBg, { backgroundColor: colors.bgCardAlt }]}>
            <View
              style={[styles.rateBarFill, { width: `${resolutionRate}%`, backgroundColor: colors.accent }]}
            />
          </View>
          <Text style={[styles.rateSub, { color: colors.textMuted }]}>
            {stats.resolved} resolved of {stats.total} total
          </Text>
        </View>

        {/* Top Category */}
        {topCategory && (
          <View style={[styles.topCatCard, { backgroundColor: colors.bgCard, borderColor: colors.border }]}>
            <View
              style={[
                styles.topCatIcon,
                {
                  backgroundColor:
                    getCategoryConfig(colors)[topCategory[0]]?.bg || colors.bgCard,
                },
              ]}
            >
              <Ionicons
                name={getCategoryConfig(colors)[topCategory[0]]?.icon || "alert-circle"}
                size={22}
                color={getCategoryConfig(colors)[topCategory[0]]?.color || colors.primary}
              />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={[styles.topCatLabel, { color: colors.textMuted }]}>Most Reported Category</Text>
              <Text style={[styles.topCatName, { color: colors.textPrimary }]}>{topCategory[0]}</Text>
            </View>
            <Text style={[styles.topCatCount, { color: colors.primary }]}>{topCategory[1]}</Text>
          </View>
        )}

        {/* Urgent Section */}
        {urgent.length > 0 && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Text
                style={[styles.sectionTitle, { color: colors.statusRejected }]}
              >
                🚨 Urgent — Needs Action
              </Text>
              <View style={[styles.sectionCount, { backgroundColor: colors.statusRejected + "22" }]}>
                <Text style={{ color: colors.statusRejected, fontSize: rf(10), fontWeight: '700' }}>{urgent.length}</Text>
              </View>
            </View>
            {urgent.slice(0, 3).map((c) => (
              <TouchableOpacity
                key={c.id}
                style={[styles.urgentRow, { backgroundColor: colors.statusRejected + "11", borderColor: colors.statusRejected + "33" }]}
                onPress={() =>
                  navigation.navigate("AdminConcernDetail", { concernId: c.id })
                }
              >
                <View style={styles.urgentLeft}>
                  <View style={[styles.urgentDot, { backgroundColor: colors.statusRejected }]} />
                  <View style={{ flex: 1 }}>
                    <Text style={[styles.urgentTitle, { color: colors.textPrimary }]} numberOfLines={1}>
                      {c.title}
                    </Text>
                    <Text style={[styles.urgentMeta, { color: colors.textMuted }]}>
                      {c.user_name} · {c.user_barangay}
                    </Text>
                  </View>
                </View>
                <Ionicons
                  name="chevron-forward"
                  size={18}
                  color={colors.textMuted}
                />
              </TouchableOpacity>
            ))}
            {urgent.length > 3 && (
              <TouchableOpacity
                onPress={() => navigation.navigate("AdminConcerns")}
              >
                <Text style={[styles.seeAll, { color: colors.primary }]}>
                  See all {urgent.length} urgent →
                </Text>
              </TouchableOpacity>
            )}
          </View>
        )}

        {/* Recent Concerns */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={[styles.sectionTitle, { color: colors.textPrimary }]}>🕐 Recent Concerns</Text>
            <TouchableOpacity
              onPress={() => navigation.navigate("AdminConcerns")}
            >
              <Text style={[styles.seeAll, { color: colors.primary }]}>See all →</Text>
            </TouchableOpacity>
          </View>
          {recent.map((c) => {
            const cfg = getStatusConfig(colors)[c.status] || getStatusConfig(colors)["Pending"];
            const catCfg =
              getCategoryConfig(colors)[c.category] || getCategoryConfig(colors)["Other"];
            return (
              <TouchableOpacity
                key={c.id}
                style={[styles.concernRow, { backgroundColor: colors.bgCard, borderColor: colors.border }]}
                onPress={() =>
                  navigation.navigate("AdminConcernDetail", { 
                    concernId: c.id,
                    concernIds: recent.map(r => r.id)
                  })
                }
              >
                <View style={[styles.catDot, { backgroundColor: catCfg.bg }]}>
                  <Ionicons name={catCfg.icon} size={16} color={catCfg.color} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={[styles.concernTitle, { color: colors.textPrimary }]} numberOfLines={1}>
                    {c.title}
                  </Text>
                  <Text style={[styles.concernMeta, { color: colors.textMuted }]}>
                    {c.user_name} · {c.user_barangay}
                  </Text>
                </View>
                <View style={[styles.statusPill, { backgroundColor: cfg.bg }]}>
                  <Text style={[styles.statusPillText, { color: cfg.color }]}>
                    {c.status}
                  </Text>
                </View>
              </TouchableOpacity>
            );
          })}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { padding: scale(20), paddingBottom: verticalScale(40) },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(20),
  },
  greeting: { fontSize: rf(14), fontWeight: "600" },
  adminName: {
    fontSize: rf(20),
    fontWeight: "800",
    marginTop: verticalScale(2),
  },
  exportBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: scale(6),
    borderRadius: moderateScale(20),
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(6),
    borderWidth: 1,
  },
  exportText: { fontSize: rf(12), fontWeight: "700" },

  kpiGrid: { flexDirection: "row", gap: scale(10), marginBottom: verticalScale(14) },
  kpiCard: {
    flex: 1,
    borderRadius: moderateScale(14),
    padding: scale(12),
    alignItems: "center",
    borderWidth: 1,
    borderTopWidth: 3,
  },
  kpiIcon: { fontSize: rf(18), marginBottom: verticalScale(4) },
  kpiNum: { fontSize: rf(22), fontWeight: "900" },
  kpiLabel: { fontSize: rf(10), marginTop: verticalScale(2) },

  rateCard: {
    borderRadius: moderateScale(14),
    padding: scale(16),
    borderWidth: 1,
    marginBottom: verticalScale(14),
  },
  rateHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(10),
  },
  rateTitle: { fontSize: rf(14), fontWeight: "700" },
  ratePercent: { fontSize: rf(20), fontWeight: "900" },
  rateBarBg: {
    height: verticalScale(8),
    borderRadius: scale(4),
    marginBottom: verticalScale(8),
  },
  rateBarFill: { height: verticalScale(8), borderRadius: scale(4) },
  rateSub: { fontSize: rf(11) },

  topCatCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: scale(12),
    borderRadius: moderateScale(14),
    padding: scale(14),
    borderWidth: 1,
    marginBottom: verticalScale(20),
  },
  topCatIcon: {
    width: scale(44),
    height: scale(44),
    borderRadius: moderateScale(12),
    alignItems: "center",
    justifyContent: "center",
  },
  topCatLabel: { fontSize: rf(11) },
  topCatName: {
    fontSize: rf(14),
    fontWeight: "700",
    marginTop: verticalScale(2),
  },
  topCatCount: { fontSize: rf(24), fontWeight: "900" },

  section: { marginBottom: verticalScale(20) },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: verticalScale(12),
  },
  sectionTitle: { fontSize: rf(16), fontWeight: "700" },
  sectionCount: {
    borderRadius: moderateScale(10),
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(2),
  },
  seeAll: {
    fontSize: rf(13),
    fontWeight: "700",
    marginTop: verticalScale(8),
    textAlign: "right",
  },

  urgentRow: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: moderateScale(12),
    padding: scale(12),
    borderWidth: 1,
    marginBottom: verticalScale(8),
  },
  urgentLeft: { flex: 1, flexDirection: "row", alignItems: "center", gap: scale(10) },
  urgentDot: {
    width: scale(10),
    height: scale(10),
    borderRadius: scale(5),
  },
  urgentTitle: { fontSize: rf(14), fontWeight: "600" },
  urgentMeta: { fontSize: rf(11), marginTop: verticalScale(2) },

  concernRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: scale(12),
    borderRadius: moderateScale(12),
    padding: scale(12),
    borderWidth: 1,
    marginBottom: verticalScale(8),
  },
  catDot: {
    width: scale(38),
    height: scale(38),
    borderRadius: moderateScale(10),
    alignItems: "center",
    justifyContent: "center",
  },
  concernTitle: { fontSize: rf(13), fontWeight: "600" },
  concernMeta: { fontSize: rf(11), marginTop: verticalScale(2) },
  statusPill: { paddingHorizontal: scale(8), paddingVertical: verticalScale(4), borderRadius: moderateScale(20) },
  statusPillText: { fontSize: rf(10), fontWeight: "700" },
});
